routes/user.php
<?php
/**
 * Created by PhpStorm.
 * User: diego
 * Date: 26/9/17
 * Time: 09:53
 */
Route::post('participar','JoinController@participar')->name('join.created');
Route::post('addVaucher','BuyController@addVoucherToPerson')->name('add.voucher');
Route::post('addPersonToBuy','JoinController@addPersonToBuy')->name('add.personbuy');
Route::get('perfil','PersonController@editPerfil')->name('person.edit_perfil');
Route::put('perfil/{id}/update','PersonController@updatePerfil')->name('person.update_perfil');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('confirmation/{token}','Auth\RegisterController@getConfirmation')->name('confirmation');
Route::get('logout','Auth\LoginController@logout')->name('logout');
Route::get('/', 'HomeController@index')->name('home');
Route::get('home', 'HomeController@dashboardUser')->name('dashboad.user');
Route::get('adminhome', 'HomeController@dashboadAdmin')->name('dashboad.admin');

Route::get('/beneficios', 'HomeController@beneficios')->name('beneficios');
Route::get('/concursos', 'HomeController@concursos')->name('concursos');
Route::get('/concursosj', 'HomeController@concursosj')->name('concursosj');
Route::get('/beneficiosj', 'HomeController@beneficiosj')->name('beneficiosj');

Route::get('/concursos/{slug}','HomeController@show')->name('draws.show');
Route::get('/beneficios/{slug}','HomeController@showbeneficit')->name('benefict.show');
Route::post('/sorteo/preparticipe','HomeController@preparticipe')->name('join.preparticipe');
Route::post('/beneficios/prebuy','HomeController@prebuy')->name('benefict.prebuy');


Route::get('countries', 'CountryController@getCountries');
Route::get('states/{id}', 'StateController@getStates');
Route::get('districs/{id}', 'DistrictController@getDistricts');
Route::get('towns/{id}', 'TownController@getTowns');
Route::get('about','HomeController@about')->name('about');
Route::get('contacto','HomeController@contact')->name('contact');

//api rutas publicas
Route::get('/concursosj', 'APIControllers\HomeControllerApi@concursosj')->name('concursosj');
Route::get('/beneficiosj', 'APIControllers\HomeControllerApi@beneficiosj')->name('beneficiosj');
Route::get('/getLastChangeDraw','APIControllers\HomeControllerApi@getLastChangeDraw');
Route::get('/getLastChangeBuy','APIControllers\HomeControllerApi@getLastChangeBuy');
Route::post('/apiregister','APIControllers\RegisterControllerApi@register')->name('registration.api');
Route::get('/apiconfirmation/{token}','APIControllers\RegisterControllerApi@getConfirmation')->name('confirmation.api');

Route::get('/apistates/{id}', 'APIControllers\AddressControllerApi@getStates');
Route::get('/apidistrics/{id}', 'APIControllers\AddressControllerApi@getDistricts');

app/Models/Buy.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;

class Buy extends Entity
{
    //
    protected $table = 'buys';

    protected $fillable = [
      'slug', 'url', 'name', 'description','metadescription','date_init','date_finish','avatar','alt','status','delete','price_total','percent','price_discount','date_specific','time_specific','check_date_especific','check_date_period'
    ];

    public function persons(){
        return $this->belongsToMany(Person::class,'buys_persons')
                    ->withTimestamps();
    }

    public function getAvatarAttribute($value){
        return str_replace('public/','',$value);
    }

    public function getDateInitAttribute(){
        if (!is_null($this->attributes['date_init'])) {
            return date('d/m/Y', strtotime(str_replace('-', '/', $this->attributes['date_init'])));
        }
        return null;
    }

    public function getDateSpecificAttribute(){
        if (!is_null($this->attributes['date_specific'])) {
            return date('d/m/Y', strtotime(str_replace('-', '/', $this->attributes['date_specific'])));
        }
        return null;
    }

    public function getDateFinishAttribute(){
        if (!is_null($this->attributes['date_finish'])){
            return date('d/m/Y',strtotime(str_replace('-','/',$this->attributes['date_finish'])));
        }
        return null;
    }

    public function getDateSpecific(){
        if (!is_null($this->attributes['date_specific'])) {
            return Carbon::createFromFormat('Y-m-d', $this->attributes['date_specific'])->format('d/m/Y');
        }
        return null;
    }

    public function getTimeSpecific(){
        if (!is_null($this->attributes['time_specific'])) {
            return Carbon::createFromFormat('H:i:s', $this->attributes['time_specific'])->format('g:i A');
        }
        return null;
    }


    public function getDate(){
        if (!is_null($this->attributes['date_specific'])){
            return  Carbon::createFromFormat('Y-m-d', $this->attributes['date_specific'])->format('m-d-Y');
        }
        return null;

    }

    public function getTime(){
        if (!is_null($this->attributes['time_specific'])){
            return Carbon::createFromFormat('H:i:s', $this->attributes['time_specific'])->format('H:i:s');
        }
        return null;
    }

    public function getTimeDate(){
        return $this->getDate().' '.$this->getTime();
    }

    public function scopeLastChangeBuy($query)
    {
        return $query->orderby('created_at','DESC')->take(3)->get();
    }

    public function codes(){
        return $this->hasMany(Code::class);
    }

    public function isExpired()
    {
            if ( $this->attributes['date_specific'] == Carbon::now()->format('Y-m-d') && Carbon::createFromFormat('H:i:s',$this->attributes['time_specific'])->format('g:i A') <= Carbon::now()->format('g:i A')){
                return true;
            }

        return false;
    }
}

app/Http/Controllers/BuyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\BuyRequest;
use App\Http\Requests\UpdateBuyRequest;
use App\Models\Buy;
use App\Repositories\BuyRespository;
use App\Repositories\PersonRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Redirect;
use Yajra\DataTables\Facades\DataTables;
use Alert;

class BuyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $buyRespository;
    protected $personRepository;

    public function __construct(BuyRespository $buyRespository, PersonRepository $personRepository)
    {
        $this->middleware('auth');
        $this->buyRespository = $buyRespository;
        $this->personRepository = $personRepository;

    }

    public function index()
    {
        //
        return view('admin.buys.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.buys.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(BuyRequest $request)
    {
        //
        $buy = $this->buyRespository->created($request);
        $notification = [
            'message'    => 'Se ha creado un nuevo beneficio '.$buy->name,
            'alert-type' => 'success'
        ];

        return Redirect::to(route('buys.index'))->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        if (ctype_digit($id) && !is_null($id)) {
            $buy = $this->buyRespository->findForId($id);
            return view('admin.buys.show', compact('buy'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->authorize('edit', $this->buyRespository->findForId($id));
        //
        if (ctype_digit($id) && !is_null($id)) {
            $buy = $this->buyRespository->findForId($id);
            return view('admin.buys.edit', compact('buy'));
        }

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBuyRequest $request, $id)
    {
        //
        $buy = $this->buyRespository->updated($request, $id);
        $notification = [
            'message'    => 'Se ha modificado el beneficio '.$buy->name,
            'alert-type' => 'success'
        ];

        return Redirect::to(route('buys.index'))->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        if (ctype_digit($id) && !is_null($id)) {
            $this->buyRespository->destroy($id);
        }
    }

    public function active($id)
    {
        if (ctype_digit($id) && !is_null($id)) {
            $buy = $this->buyRespository->findForId($id);
            $buy->status = true;
            $buy->save();
        }
    }

    public function desactive($id)
    {
        if (ctype_digit($id) && !is_null($id)) {
            $buy = $this->buyRespository->findForId($id);
            $buy->status = false;
            $buy->save();
        }
    }


    public function getBuys()
    {
        $buys = $this->buyRespository->getBuys();

        return DataTables::eloquent($buys)
                         ->addColumn('action', function () {
                             return $this->btnsBuys();
                         })
                         ->make(true);
    }


    public function btnsBuys()
    {

        return ' 
        <div style="display: flex;">
            <div class="input-group-btn">
                <button data-toggle="dropdown" class="btn btn-primary dropdown-toggle" type="button"><i class="fa fa-bars"></i> <span class="caret"></span></button>
                <ul class="dropdown-menu pull-right">
                    <li><a data-toggle="modal" data-target="#modalShow"class="btn btn-xs show"><i class="glyphicon glyphicon-eye-open"></i> Ver</a></li>
                    '.$this->canEditBuy().'
                    <li><a data-toggle="modal" data-target="#modalDelete"  class="btn btn-xs delete"><i class="glyphicon glyphicon-trash"></i> Eliminar</a></li>
        
                </ul>
                <a data-toggle="modal" data-target="#modalParticipantsb" class="btn  btn-info  participantsb " ><i class="fa fa-users"></i></a>

            </div>
        </div>';
    }

    /*
     * Recupera todos los beneficios tanto inactivos o activos ordenados por fechas de creacion,
     * se muestra en el front-end del administrador
     *
     * */
    public function canEditBuy()
    {

        if (Gate::allows('edit', Buy::class)) {
            return '<li><a data-toggle="modal" data-target="#modalEdit" class="btn btn-xs  edit"><i class="glyphicon glyphicon-edit"></i> Editar</a></li>';
        }

        return '';
    }

    public function addVoucherToPerson(Request $request)
    {
        $person = $this->personRepository->find($request->input('person_id'));
        if ($this->buyRespository->exitsPerson($person, $request->input('buy_id'))) {
            Alert::warning('Usted ya accedió a este voucher', 'Aviso')->autoclose(4000);;

            return Redirect::to($request->session()->previousUrl());
        }
        $this->buyRespository->join($request, $person);

        Alert::success('Usted puede acceder al código de descuento', 'Listo')->autoclose(4000);;

        return Redirect::to($request->session()->previousUrl());
    }

    /*
     * Recupera todos los participantes de un determinado beneficio
     * */
    public function getParticipants($id)
    {
        return $this->buyRespository->getParticipants($id);
    }

    public function participants($id)
    {
        //
        $buy = $this->buyRespository->find($id);
        return view('admin.buys.participants', compact('buy'));
    }

}

resources/views/client/buys/show.blade.php
@section('meta-title',$buy->name)
@section('meta-description', $buy->metadescription)
@include('includes.analitics')
@push('seo')
<meta property="og:title" content="{{$buy->name}}">
<meta property="og:url" content="{{request()->url()}}"/>
<meta property="og:image" content="{{asset('/storage/'.$buy->avatar)}}"/>
<meta property="og:description" content="{{$buy->metadescription}}"/>

@endpush

@extends('layouts.app')
@push('styles')
<link href="{{ asset('/plugins/totime/timeTo.css') }}" rel="stylesheet"/>
@endpush
@section('content')


    <div class="container">

        <br>
        <br>
        <br>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form">
                    <div class="row well">
                        <div class="col-md-12"><!-- image -->
                            <!-- carousel -->

                            <h1 style="font-size: 28px;text-align: center;">

                                {{$buy->name}}
                            </h1>
                        </div>
                        <div class="col-md-6">
                                <img class="img-responsive" src="/storage/{{$buy->avatar}}" alt="{{$buy->alt}}">
                        </div>
                        <div class="col-md-6" style="">
                            @if(is_null($buy->date_init))
                            <div class="row">
                                <br class="hidden-md">
                                <h3 style="text-align: center;">
                                    {{--<div id="getting-started"></div>--}}
                                    <div id="countdown" class="" data-value=""></div>
                                </h3>
                            </div>
                            @endif
                            @if(!is_null($buy->percent))

                                <div class="row">

                                    <h3 style="text-align: center;"><span class="label label-danger">{{$buy->percent}}
                                            % de descuento</span>
                                    </h3>
                                </div>
                            @endif
                            <div class="row">
                                <h3 style="text-align: center;">
                                    <span class="label label-default"><s>$ {{$buy->price_total}}</s></span>
                                </h3>
                            </div>
                            <div class="row">
                                <h2 style="text-align: center;"><span
                                            class="label label-success">$ {{$buy->price_discount}}</span>
                                </h2>
                            </div>
                            <div class="row" style="text-align: center; margin-top: -20px;">
                                @auth
                                @if(Auth::user())
                                    @if(is_null($buy->getDateSpecific()))
                                        @if(!is_null(Auth::user()->person()))
                                        <form id="form" class="form" method="POST" action="{{route('add.personbuy')}}">
                                            {!! csrf_field() !!}
                                            <input type="hidden" id="id" name="buy_id" value="{{$buy->id}}">
                                            <input type="hidden" id="id" name="person_id"
                                                   value="{{Auth::user()->person()->first()->id}}">
                                            <button type="submit"
                                               class="btn btn-lg btn-default btn-bordered fs-15"><i
                                                        class="fa fa-shopping-cart"></i>
                                                COMPRAR
                                            </button>
                                        </form>
                                            @endif
                                    @else
                                        @if(!Auth::user()->person->buys->contains($buy))

                                            <form id="form" class="form" method="POST"
                                                  action="{{route('add.voucher')}}">
                                                {!! csrf_field() !!}
                                                <input type="hidden" id="id" name="buy_id" value="{{$buy->id}}">
                                                <input type="hidden" id="id" name="person_id"
                                                       value="{{Auth::user()->person()->first()->id}}">

                                                <button type="submit"
                                                        class="btn btn-lg btn-default btn-bordered fs-15">
                                                    OBTENER CUPÓN
                                                </button>
                                            </form>
                                        @else
                                            @if(!is_null($buy->code))

                                                <label
                                                        class="">
                                                    <b>ESTE ES TU CÓDIGO DEL CUPÓN DE DESCUENTO</b>
                                                </label>
                                                <div class=" alert-success ">
                                                    {{$buy->code}}
                                                </div>
                                                <label>
                                                    <b>COPIÁ TU CÓDIGO Y HACE CLICK EN COMPRAR</b>
                                                </label>
                                                <form id="form" class="form">
                                                    <a href="{{$buy->url}}" target="_blank" type="button"
                                                       class="btn btn-lg btn-default btn-bordered fs-15"><i
                                                                class="fa fa-tag"></i>
                                                        COMPRAR
                                                    </a>
                                                </form>
                                            @endif

                                        @endif
                                    @endif
                                @endif
                                @else
                                    @if(is_null($buy->getDateSpecific()))

                                        <form id="form" class="form" method="post"
                                              action="{{route('benefict.prebuy')}}">
                                            {!! csrf_field() !!}
                                            <input type="hidden" name="buy_id" value="{{$buy->id}}">
                                            <button class="btn btn-lg btn-default btn-bordered"
                                                    type="submit"><i
                                                        class="fa fa-shopping-cart"></i>COMPRAR
                                            </button>
                                        </form>
                                    @else
                                        <form id="form" class="form" method="post"
                                              action="{{route('benefict.prebuy')}}">
                                            {!! csrf_field() !!}
                                            <input type="hidden" name="buy_id" value="{{$buy->id}}">
                                            <button class="btn btn-lg btn-default btn-bordered"
                                                    type="submit"><i
                                                        class="fa fa-tag"></i> OBTENER CUPÓN
                                            </button>
                                        </form>
                                    @endif


                                    @endauth


                            </div>

                        </div>
                        <div class="col-md-12">
                            <div class="row" style="margin-top: -30px;">
                                <br>
                                <br>

                                <div align="justify">{!! $buy->description !!}</div>
                                @if(!is_null($buy->date_init))
                                    <ul class="list-unstyled">
                                        <li>
                                            <i class="fa fa-check"></i>
                                            <strong>Periodo del beneficio:</strong> {{$buy->date_init}}
                                            - {{$buy->date_finish}}
                                        </li>

                                    </ul>
                                @else
                                    <ul class="list-unstyled">
                                        <li>
                                            <i class="fa fa-check"></i>
                                            <strong>Fecha de vencimiento:</strong> {{$buy->date_specific}}
                                        </li>
                                        <li>
                                            <i class="fa fa-check"></i>
                                            <strong>Hora de vencimiento:</strong> {{$buy->getTimeSpecific()}}
                                        </li>
                                    </ul>
                                @endif
                            </div>

                        </div>

                    </div>
                    <div class="container">
                    </div>
                </div>
            </div>
        </div>
        <!-- /item -->
    </div>

@endsection
@push('scripts')
<script src="{{ asset('/plugins/totime/jquery.time-to.js')}}"></script>
<script src="{{ asset('/plugins/countdown/jquery.countdown.js')}}"></script>

<script>
    var ti = {!! json_encode($buy->getTimeDate()) !!};
    console.log(ti);
    $('#countdown').timeTo({
        timeTo: new Date(new Date(ti + ' GMT-0300')),
        displayDays: 2,
        theme: "black",
        displayCaptions: true,
        fontSize: 30,
        captionSize: 14,
        languages: {
            pl: {days: 'días', hours: 'horas', min: 'minutos', sec: 'segundos'}
        },
        lang: 'pl'
    });
    $("#getting-started")
        .countdown('2020/10/10', function (event) {
            $(this).html(event.strftime('%D days %H:%M:%S'));
        });

</script>
@endpush